---
- name: include variable os overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: include variable architecture overrides
  include_vars: "{{ item }}"
  with_items:
    - "vars/{{ ansible_machine }}.yml"

- name: create packer directory
  file:
    dest: "{{ packer_path }}"
    state: directory

- name: download packer
  get_url:
    url: "{{ packer_url }}"
    dest: "{{ packer_path }}"

- name: extract packer binaries
  unarchive:
    copy: no
    src: "{{ packer_path }}/{{ packer_file }}"
    dest: "{{ packer_path }}"
    creates: "{{ packer_path }}/packer"
  changed_when: false
  tags:
    - ignore_testinfra

- name: create shell configuration files
  template:
    dest: "{{ packer_conf_file }}"
    src: "{{ packer_conf_template }}"
    force: no
  when: packer_conf_file is defined

- name: configure packer path
  lineinfile:
    dest: "{{ packer_conf_file }}"
    line: '[[ -d {{ packer_path }} ]] && export PATH="{{ packer_path }}:$PATH"'
